### ISSUE TITLE
Importing new spreadsheet occasionally doesn't work

### ISSUE THREAD

**Issue by kaiwolf26** [wolfpaq/keyword-clip#11]
Categories didn't update on the new installation, and when I tried to import a new copy of the spreadsheet it didn't work, but loading a different older copy worked.

**Comment by wolfpaq** [comment]
I've tried importing old and new versions and haven't had any problems. When you say it "didn't work" did you get an error or you're just not seeing the new data that you expect. One thing you can try is to open the Developer Tools using the View menu. In the console tab of the developer tools, can you see any errors after a failed import?

As for a new installation not picking up the new spreadsheet, I think I'm going to make it an option to delete the old spreadsheet which is saved in local storage. I save it there so that once a user imports their own spreadsheet, I didn't want to overwrite that each time the app starts.

**Comment by kaiwolf26** [comment]
Yeah, I'm not seeing the data I expect.
The console tab isn't showing any errors when I try to import either.

**Comment by wolfpaq** [comment]
The sheet name changed in the latest version. I now just import the first sheet no matter what so the import should be fixed.

If you get a new version of the app and you have previously imported a different spreadsheet I do not overwrite the previous version automatically. Instead, you can open the Settings dialog and select the "Reset category list to default." checkbox and click OK. This will throw away the spreadsheet you had previously imported and revert to the default spreadsheet data that comes with the app.
